### ISSUE TITLE
Pagination with $limit 

### ISSUE THREAD

**Issue by rdewolff** [KapMug/feathers-nano#12]
Hey @KoderPex and @bazaglia 

What repo are you using for this project? Is this one the last version of it?

Am trying to use create queries with the `$limit` parameter but am getting an error.

Am testing it with a REST query as follow :

`curl -X GET http:localhost:3030/myService?$skip=3`

But I get the following error: 

```
<<50>> is not an integer greater than or equal to zero
```

**Comment by bazaglia** [comment]
@rdewolff This project is discontinued and was last tested with an old CouchDB version. But since it's a database adapter it should follow the common way for querying as all in Feathers docs:

https://docs.feathersjs.com/api/databases/querying.html#limit

By the way, `$skip` is how FeathersJS treats it at the adapter level. The REST API CouchDB exposes uses `skip`. Documentation reference (with example):

https://docs.couchdb.org/en/stable/api/database/find.html?highlight=skip#db-find
